/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Sharex } from "./Sharex";
export * as factories from "./factories";
export { Sharex__factory } from "./factories/Sharex__factory";
